#!/usr/bin/env python

import sys,shutil

# source given as a first argument from emailrelay
source_path = sys.argv[1]

# copy to 'storage' directory in the script's dir
dest_path = '/'.join(sys.argv[0].split('/')[:-1])+'/storage/'+sys.argv[1].split('/')[-1]

shutil.copy(source_path, dest_path)
